apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-parameters-appset
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: global-parameters
    repoURL: ssh://git@github.com/marcinkwapiszcomarch/test
    targetRevision: HEAD
    plugin:
      parameters:
        - name: values-files
          array:
            - deployments/values.yaml
  project: cdi-base
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
