apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-parameters-appset
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: cdi-base
  source:
    # TODO: Replace with your actual Git repository URL
    repoURL: ssh://git@github.com/marcinkwapiszcomarch/test
    targetRevision: HEAD
    path: global-parameters
  syncPolicy:
    syncOptions:
      - CreateNamespace=true