apiVersion: v2
name: global-parameters
description: Simple Helm chart for testing global parameters
type: application
version: 0.1.0
appVersion: "1.0.0"
annotations:
  chart.requirements/argocd-vault-plugin: "true"

