apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test2
stringData:
  test-value: {{ .Values.clusterName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test-avp
stringData:
  sprawdzam_wartosc: "<path:cdi/tools/logging/cognito#kibanaClientID>"
